### ISSUE TITLE
Change button text to "Add".

### ISSUE THREAD

**Issue by imsamuel** [imsamuel/note-taker#1]
Currently the button text is "Add To Notes", it should be "Add" only (see https://imsamuel.github.io/note-taker). 

Relevant code can be found at `src/components/NoteTakingForm.jsx`.

**Comment by Rupinderjeet2004** [comment]
I can do this, please assign this to me.

**Comment by imsamuel** [comment]
> I can do this, please assign this to me.

Assigned!

**Comment by 0day-anon** [comment]
Please check the PR. If anything is wrong please let me know.

**Comment by imsamuel** [comment]
> Please check the PR. If anything is wrong please let me know.

Have merged and thanks!
